### ISSUE TITLE
Licensing change to CC BY-SA 4.0

### ISSUE THREAD

**Issue by gibbed** [xenia-project/wiki#1]
The Xenia wiki was never explicitly licensed.

I'd like to ask everyone that has commits in the `wiki` repository (a clone of the former [hidden `xenia-wiki` repo](https://github.com/xenia-project/xenia.wiki.git) with vandalism and the deprecated Compatibility List page removed) to affirm approval with licensing the wiki content under [CC BY-SA 4.0](https://github.com/xenia-project/xenia/blob/master/assets/icon/LICENSE), as Xenia's logo/icon is.

*Except where this isn't possible/content that isn't ours, such as game screenshots, which will be appropriately marked as such.*

Contributors needed to approve this change:
- [x] @benvanik
- [x] @gibbed
- [x] @Triang3l
- [x] @Margen67
- [x] @illusion0001
- [x] @Gliniak
- [x] @ZolaKluke
- [x] @Razzile
- [x] @Lolihunter1337
- [x] ~~@FranciscoCarlosJR~~ **Commits removed.**
- [x] @KogaraDigital
- [x] @madmodder123
- [x] ~~@xkclxk~~ **Commits removed.**
- [x] ~~@dominikdalek~~ **Commits removed.**

If there isn't a response in sufficient time by anyone in this list or they voice their disapproval, will move forward by removing or otherwise replacing the content that person contributed.

**Comment by gibbed** [comment]
Approved (just for clarity/not in the issue itself)

**Comment by nyannoying1337** [comment]
I approve

**Comment by illusionyy** [comment]
I approve 👍

**Comment by Margen67** [comment]
I approve.

**Comment by halotroop2288** [comment]
I pre-approve for the edits I'll be making. 👍🏻😄

**Comment by ZolaKluke** [comment]
I approve

**Comment by madmodder123** [comment]
I approve

**Comment by Gliniak** [comment]
I approve

**Comment by Razzile** [comment]
I approve

**Comment by Triang3l** [comment]
~~Me gusta~~ I approve

**Comment by benvanik** [comment]
I approve!

**Comment by KogaraDigital** [comment]
I approve

**Comment by gibbed** [comment]
History has been rewritten to remove commits by FranciscoCarlosJR, xkclxk, dominikdalek since they have not responded in an adequate amount of time.
